# Generated by Django 2.2.5 on 2019-10-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_taskdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='task_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
