# Generated by Django 2.2.5 on 2019-10-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191002_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='task_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
