# Generated by Django 2.2.5 on 2019-10-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191002_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='task_name',
        ),
    ]
